import { chromium } from 'playwright-core';
import { readFileSync } from 'node:fs';
const credentials = JSON.parse(readFileSync('../../.runtime/ai-test-admin.json', 'utf8'));
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const page = await browser.newPage({ viewport: { width: 1500, height: 950 } });
await page.goto('http://127.0.0.1:5310/umbraco');
await page.locator('input[type=email], input[name=username]').first().fill(credentials.email);
await page.locator('input[type=password]').first().fill(credentials.password);
await page.keyboard.press('Enter');
await page.waitForURL(/section/);
await page.goto('http://127.0.0.1:5310/umbraco/section/ai-assistant');
const dash = page.locator('ligata-ai-dashboard');
await dash.locator('h1').waitFor();
await dash.locator('nav.tabs button', { hasText: 'Behaviour' }).click();
const email = dash.locator('label.control', { hasText: 'Contact email' }).locator('input');
console.log('count', await email.count(), 'value', await email.inputValue());
await email.fill('nope');
await page.waitForTimeout(300);
console.log('dirty', await dash.evaluate(el => el.dirty), 'busy', await dash.evaluate(el => el.busy), 'fallback', await dash.evaluate(el => el.settings.identity.fallbackEmail));
console.log('button disabled', await dash.locator('button', { hasText: 'Save changes' }).isDisabled());
await page.screenshot({ path: '../../.runtime/e2e/debug.png' });
await browser.close();
