using System.Text.Json;
using System.Text.Json.Serialization;

namespace Ligata.AI.Models;

public static class AssistantJson
{
    public static readonly JsonSerializerOptions Options = new(JsonSerializerDefaults.Web) { DefaultIgnoreCondition = JsonIgnoreCondition.Never };
    public static string Write<T>(T value) => JsonSerializer.Serialize(value, Options);
    public static T Read<T>(string value) => JsonSerializer.Deserialize<T>(value, Options)!;
}

/// <summary>Everything an editor configures in the AI Assistant section. Stored as one JSON document.</summary>
public sealed record AssistantSettings
{
    public bool Enabled { get; init; }
    public AssistantIdentity Identity { get; init; } = new();
    public AssistantBehaviour Behaviour { get; init; } = new();
    public AssistantAppearance Appearance { get; init; } = new();
    public AssistantDisplay Display { get; init; } = new();
    public string GatewayUrl { get; init; } = "http://127.0.0.1:1210";

    /// <summary>What a browser may see: no prompts, no knowledge, no gateway details.</summary>
    public object Public(int contextLimit, object limits, int baseTokens) => new
    {
        Identity.Name, Identity.Greeting, Identity.Suggestions, Identity.AvatarUrl, Identity.Language, Identity.InputPlaceholder,
        Identity.PrivacyNotice, Identity.PrivacyUrl, Identity.FallbackMessage, Identity.FallbackEmail, Identity.FallbackUrl,
        Appearance, Behaviour.AllowImages, Behaviour.AllowPdfs, ContextLimit = contextLimit, Limits = limits, BaseTokens = baseTokens,
    };
}

public sealed record AssistantIdentity
{
    public string Name { get; init; } = "Assistant";
    public string Greeting { get; init; } = "Hi! I can answer questions about this website. How can I help?";
    public List<string> Suggestions { get; init; } = [];
    public string AvatarUrl { get; init; } = "";
    /// <summary>Interface language: auto (browser), en, de, fr, it.</summary>
    public string Language { get; init; } = "auto";
    public string InputPlaceholder { get; init; } = "";
    public string PrivacyNotice { get; init; } = "Answers are generated by an AI on our own server and can be wrong. Messages are not stored.";
    public string PrivacyUrl { get; init; } = "";
    public string FallbackMessage { get; init; } = "The assistant is not available right now.";
    public string FallbackEmail { get; init; } = "";
    public string FallbackUrl { get; init; } = "";
}

public sealed record AssistantBehaviour
{
    /// <summary>The site owner's own instructions, appended to Ligata's guardrails.</summary>
    public string Instructions { get; init; } = "";
    public string SiteName { get; init; } = "";
    /// <summary>friendly | professional | concise | playful</summary>
    public string Tone { get; init; } = "friendly";
    /// <summary>short | balanced | detailed</summary>
    public string AnswerLength { get; init; } = "balanced";
    public bool StayOnTopic { get; init; } = true;
    public bool UseMarkdown { get; init; } = true;
    public bool Thinking { get; init; }
    public double Temperature { get; init; } = 0.7;
    public int MaxAnswerTokens { get; init; } = 1024;
    /// <summary>Maximum tokens of one conversation, including instructions and knowledge.</summary>
    public int ContextLimit { get; init; } = 65536;
    /// <summary>Maximum tokens of enabled knowledge.</summary>
    public int KnowledgeBudget { get; init; } = 24576;
    public bool AllowImages { get; init; } = true;
    public bool AllowPdfs { get; init; } = true;
    public bool IncludePageContext { get; init; } = true;
}

public sealed record AssistantAppearance
{
    /// <summary>ligata | midnight | ocean | forest | sunset | graphite | custom</summary>
    public string Theme { get; init; } = "ligata";
    /// <summary>light | dark | auto</summary>
    public string ColorScheme { get; init; } = "light";
    /// <summary>left | right</summary>
    public string Position { get; init; } = "left";
    public string Accent { get; init; } = "#2f5bff";
    public string AccentText { get; init; } = "#ffffff";
    public string Background { get; init; } = "#ffffff";
    public string Surface { get; init; } = "#f3f4f8";
    public string Text { get; init; } = "#15171f";
    public string MutedText { get; init; } = "#5d6272";
    public string UserBubble { get; init; } = "#2f5bff";
    public string UserText { get; init; } = "#ffffff";
    public string AssistantBubble { get; init; } = "#f3f4f8";
    public string AssistantText { get; init; } = "#15171f";
    /// <summary>inherit (the website's font) | system | rounded | serif | mono</summary>
    public string Font { get; init; } = "inherit";
    public int Radius { get; init; } = 20;
    public int LauncherSize { get; init; } = 60;
    /// <summary>chat | sparkle | help | wave | avatar</summary>
    public string LauncherIcon { get; init; } = "chat";
    public string LauncherLabel { get; init; } = "";
    public int PanelWidth { get; init; } = 400;
    public int PanelHeight { get; init; } = 640;
    public int OffsetX { get; init; } = 24;
    public int OffsetY { get; init; } = 24;
    public bool ShowContextMeter { get; init; } = true;
    public bool ShowQueuePosition { get; init; } = true;
    public bool ShowBranding { get; init; } = true;
    public bool Animations { get; init; } = true;
    public string Teaser { get; init; } = "";
    public int TeaserDelaySeconds { get; init; } = 6;
    public int ZIndex { get; init; } = 2147483000;
}

public sealed record AssistantDisplay
{
    /// <summary>all | include | exclude | manual</summary>
    public string Mode { get; init; } = "all";
    /// <summary>Path prefixes for include/exclude, e.g. /kontakt/ or /shop/</summary>
    public List<string> Paths { get; init; } = [];
    public bool HideOnMobile { get; init; }
}
